const products = [
    {
        _id: '1',
        name: 'Versace Eros',
        image: 'https://img.ep-cdn.com/i/500/500/pf/pfkmloxwnavuqjisbhdg/versace-eros-men-edt-sp-100ml-cene.jpg',
        description: 'Versace Eros je muški miris koji odiše strašću i snagom. Sadrži note nane, zelene jabuke i limuna u glavi, tonke i ambrozije u srcu, te sandalovine i pačulija u bazi.',
        category: 'Muški parfemi',
        price: 7500.00,
        countInStock: 10,
        rating: 4.8,
        numReviews: 245,
    },
    {
        _id: '2',
        name: 'Xerjoff Naxos',
        image: 'https://belodore.rs/media/amasty/amoptmobile/catalog/product/cache/08cd9d1a69d3b81aa4ac293076519bc7/X/E/XE33737-2-Xerjoff_Naxos_100ml_EDP_1_1_jpg.webp',
        description: 'Xerjoff Naxos je luksuzni orijentalni miris iz Italije. Sadrži note lavande i citrusa u glavi, meda i tobacco cveta u srcu, te vanile i tonke u bazi.',
        category: 'Muški parfemi',
        price: 28000.00,
        countInStock: 5,
        rating: 4.9,
        numReviews: 132,
    },
    {
        _id: '3',
        name: 'Nishane Hacivat',
        image: 'https://www.noli.rs/wp-content/uploads/2023/11/hacivat-e1701294390792.png',
        description: 'Nishane Hacivat je uniseks miris turske nišne kuće. Sadrži note ananasa i bergamota u glavi, ylang ylanga i pačulija u srcu, te muskovog drveta i ambra u bazi.',
        category: 'Uniseks parfemi',
        price: 22000.00,
        countInStock: 8,
        rating: 4.9,
        numReviews: 189,
    },
    {
        _id: '4',
        name: 'YSL Y Eau de Parfum',
        image: 'https://jasmin.b-cdn.net/media/catalog/product/cache/4456161891bc26600241f10587ca424f/3/6/3614272050341-c86e730a-c2c6-4ab9-bd4a-2a14a3cecea7_1.jpg',
        description: 'Yves Saint Laurent Y EDP je moderni muški miris. Sadrži note bergamota i đumbira u glavi, žalfije i cedra u srcu, te ambra i tonke u bazi.',
        category: 'Muški parfemi',
        price: 8500.00,
        countInStock: 12,
        rating: 4.7,
        numReviews: 310,
    },
    {
        _id: '5',
        name: 'YSL Myself',
        image: 'https://www.parfimerijatajna.rs/files/2023/08/3614273852814_alt1.jpg',
        description: 'Yves Saint Laurent MYSLF je svež i drveni muški miris. Sadrži note bergamota i yuzu u glavi, kardamoma i neroli u srcu, te vanile i cedra u bazi.',
        category: 'Muški parfemi',
        price: 9000.00,
        countInStock: 9,
        rating: 4.6,
        numReviews: 178,
    },
    {
        _id: '6',
        name: 'Jean Paul Gaultier Le Male Elixir',
        image: 'https://www.noli.rs/wp-content/uploads/2024/10/le-male-elixir.png',
        description: 'JPG Le Male Elixir je intenzivna i senzualna verzija kultnog Le Male mirisa. Sadrži note lavande i meda u glavi, vanile i irisa u srcu, te drvenih nota u bazi.',
        category: 'Muški parfemi',
        price: 10500.00,
        countInStock: 6,
        rating: 4.8,
        numReviews: 221,
    },
    {
        _id: '7',
        name: 'Paco Rabanne 1 Million',
        image: 'https://www.lookfantastic.ie/images?url=https://static.thcdn.com/productimg/original/10643789-3185116435920954.jpg&format=webp&auto=avif&width=1200&height=1200&fit=cover',
        description: 'Paco Rabanne 1 Million je jedan od najpopularnijih muških mirisa na svetu. Sadrži note grejpfruta i nane u glavi, cimeta i ruže u srcu, te kože i pačulija u bazi.',
        category: 'Muški parfemi',
        price: 8000.00,
        countInStock: 15,
        rating: 4.7,
        numReviews: 520,
    },
    {
        _id: '8',
        name: 'Chanel Coco Mademoiselle',
        image: 'https://www.parfemilux.rs/wp-content/uploads/2023/07/IMG_1863.jpeg',
        description: 'Chanel Coco Mademoiselle je ikonski ženski miris. Sadrži note narandže i bergamota u glavi, ruže i jasmina u srcu, te pačulija i vanile u bazi.',
        category: 'Ženski parfemi',
        price: 13000.00,
        countInStock: 10,
        rating: 4.9,
        numReviews: 640,
    },
    {
        _id: '9',
        name: 'Dior Miss Dior Blooming Bouquet',
        image: 'https://www.brivane.com/cdn/shop/files/Miss_Dior_Blooming_Bouquet_Dior_for_women_-_Brivane-2718082.jpg?v=1724616792',
        description: 'Dior Miss Dior Blooming Bouquet je cvetni i svež ženski miris. Sadrži note mandarine i jagode u glavi, božura i damast ruže u srcu, te belog muskovog drveta u bazi.',
        category: 'Ženski parfemi',
        price: 11500.00,
        countInStock: 8,
        rating: 4.8,
        numReviews: 415,
    },
    {
        _id: '10',
        name: 'Lancôme La Vie Est Belle',
        image: 'https://cocoparfemi.com/cdn/shop/files/lancome-la-vie-est-belle-lelixir-parfemska-voda-punjiva-za-zene___240730.jpg?v=1730248493',
        description: 'Lancôme La Vie Est Belle je sladak i ženstveni miris. Sadrži note crne ribizle i kruške u glavi, irisa i jasmina u srcu, te pralina, vanile i pačulija u bazi.',
        category: 'Ženski parfemi',
        price: 10000.00,
        countInStock: 11,
        rating: 4.7,
        numReviews: 389,
    },
    {
        _id: '11',
        name: 'YSL Black Opium',
        image: 'https://www.parfemilux.rs/wp-content/uploads/2023/07/photo-output-41.jpeg',
        description: 'Yves Saint Laurent Black Opium je zavodljiv i adiktivan ženski miris. Sadrži note kruške i ružičastog bibera u glavi, kafe i jasmina u srcu, te vanile i pačulija u bazi.',
        category: 'Ženski parfemi',
        price: 10500.00,
        countInStock: 7,
        rating: 4.8,
        numReviews: 502,
    },
    {
        _id: '12',
        name: 'Maison Margiela Replica Flower Market',
        image: 'https://www.noli.rs/wp-content/uploads/2025/06/505fc1b4-70ee-4319-bc65-e83bfe0ac8cb-e1750082157856.jpeg',
        description: 'Maison Margiela Replica Flower Market je svež i cvetni uniseks miris inspirisan pijacama cveća. Sadrži note zelenog lista i bergamota, srca ruže i ljubičice, te baze bele cedrovine.',
        category: 'Ženski parfemi',
        price: 16000.00,
        countInStock: 4,
        rating: 4.6,
        numReviews: 167,
    },
]

export default products;